[[main]]
  identifier = "about"
  name = "O mnie"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Wpisy"
  url = "posts"
  weight = 2
    
[[main]]
  identifier = "notes"
  name = "Notatki"
  url = "notes"
  weight = 3